include: package:very_good_analysis/analysis_options.yaml
analyzer:
  language:
    strict-casts: false
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.graphql.dart"
    - "**/graphql_api.dart"
  errors:
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.graphql.dart"
    - "**/graphql_api.dart"  