name: yellow_squash
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.1.0
  flutter_screenutil: ^5.7.0
  dio: ^4.0.6
  nb_utils: ^6.0.5
  freezed_annotation: ^2.2.0
  logger: ^1.3.0
  json_serializable: ^6.5.4
  auto_route: ^6.0.5
  injectable: ^2.1.1
  get_it: ^7.2.0
  pinput: ^2.2.23
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.7+2
  shimmer: ^2.0.0
  http: ^0.13.6
  provider: ^6.0.5
  chewie: ^1.4.0
  video_player: ^2.7.1
  share_plus: ^6.3.4
  expandable: ^5.0.1
  flutter_html: ^3.0.0-beta.1
  simple_animations: ^3.1.1
  fluttertoast: ^8.0.8
  animations: ^2.0.7
  razorpay_flutter: ^1.3.5
  webview_flutter: ^4.2.2
  youtube_player_flutter: ^8.1.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.12
  dropdown_search: ^5.0.6
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.1
  animated_bottom_navigation_bar: ^1.3.0
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  flutter_svg: ^2.0.9
dependency_overrides:
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any
  
dev_dependencies:
  auto_route_generator: ^6.0.0
  bloc_test: ^9.1.1
  device_preview: ^1.1.0
  injectable_generator: ^2.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  freezed: ^2.2.0
  build_runner: ^2.3.3
  very_good_analysis: ^4.0.0+1

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/iconyellow.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  background_color: black
  web:
    generate: true
    image_path: 'assets/icons/iconyellow.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/icons/iconyellow.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/icons/iconyellow.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    # ICONS
    - assets/icons/
    - assets/icon/
    # IMAGES
    - assets/images/
